README.md, content/_index.md, content/privacy.md, content/terms.md, package-lock.json, package.json, static/manifest.json, templates/shortcodes/badge.html, templates/shortcodes/screenshot.html
=> Follow-up fixes

content/_index.tr.md
Signed-off-by: MetehanOzyurek metehanc8s9@hotmail.com
=> Translated and signed (I hope) 

content/donate/index.md
Signed-off-by: Roman Tsisyk <roman@tsisyk.com>
=> Add crypto donations

content/donate/index.md, sass/main.scss, templates/shortcodes/donate_buttons.html
Проверяем превью и мержим если ок.
=> Fixed donate layout

content/_index.md
Signed-off-by: Metehan Özyürek <metehanc8s9@hotmail.com>
=> Added Turkish group link

config.toml
@rtsisyk Надо допилить выбор языка и доперевести остальное. Ну или мержить без выбора языка, по прямым ссылкам тоже будет работать.
=> Enabled localizations

config.toml, content/_index.it.md, content/donate/index.it.md
Signed-off-by: Roman Tsisyk <roman@tsisyk.com>
=> Enable Italian

sass/main.scss, templates/menu.html
=> Fix menu to fit into one line on mobile

config.toml, sass/_language_selector.scss, sass/main.scss, templates/language_selector.html, templates/menu.html
=> Added language selector

content/_index.de.md, content/_index.it.md, content/_index.pl.md, content/_index.tr.md, content/donate/index.de.md, content/donate/index.it.md, content/support-us/index.de.md, content/support-us/index.it.md, content/support-us/index.pl.md, content/support-us/index.tr.md
Fixes #71
Signed-off-by: Mr-Mime <lennart@fabianfisahn.de>
=> Fix links on translated pages

content/_index.id.md, content/_index.md, po/content.id.po, po/content.pot, templates/shortcodes/references.md
Also sorted/moved common references in one place
=> Added Reddit

content/news/2022-12-23/122/index.cs.md
Signed-off-by: Jan Podhorsky <grreby@proton.me>
=> Add Czech latest news translation

content/donate/index.pl.md
The translator used thought "the right thing" was a brand name
=> Fix pl New Years translation

content/donate/index.tr.md
Signed-off-by: Metehan Özyürek <metehanc8s9@hotmail.com>
=> Updated Turkish Donate Page

content/news/2022-11-21/110/index.tr.md, content/news/2022-11-30/111/index.tr.md, content/news/2022-12-02/113/index.tr.md
Translated some news to Turkish:
```
* content/news/2022-11-21/110/index.md
* content/news/2022-11-30/111/index.md
* content/news/2022-12-02/113/index.md
```
=> Translated News [11-21], [11-30], [12-02] to Turkish

content/news/2023-01-27/132/index.tr.md
Signed-off-by: Metehan Özyürek <metehanc8s9@hotmail.com>
=> [01-27] minor Turkish translation fix

content/_index.md, po/content.ar.po, po/content.bn.po, po/content.ca.po, po/content.cs.po, po/content.de.po, po/content.el.po, po/content.es.po, po/content.eu.po, po/content.hi.po, po/content.hu.po, po/content.id.po, po/content.mr.po, po/content.nl.po, po/content.pl.po, po/content.pot, po/content.pt-BR.po, po/content.ru.po, po/content.uk.po, po/content.zh-Hans.po
I think the meaning was supposed to be that the trip lasts a week, not that we do one trip every week. :)
Very cool project by the way, found out about it last week and have been loving it!
=> Correct weekly -> weeklong

content/news/2023-02-14/140/index.it.md
=> [news] Italian translation 🇮🇹

.github/FUNDING.yml, .github/workflows/check.yml, .github/workflows/publish.yml, README.md, package-lock.json, package.json, templates/base.html
CF upgraded their build images. Finally.
=> Back to CF pages deployment

.github/workflows/check.yml, .github/workflows/publish.yml
Releases notes: https://github.com/actions/checkout/releases
=> Bump actions/checkout to v4

templates/base.html
Maybe for future years, we can find a way to automatically get year?
=> Update year on website for new year

content/_index.hu.md, content/_index.md
Referencing to my discussion with Alexander. A small but useful change, nothing big.
=> Add mention of translator communities (yet only Hungarian)

content/faq/app/which-ios-and-android-versions-are-supported/index.es.md, content/faq/text-to-speech-android-tts/index.es.md
[faq] Fix link in Spanish App FAQ
=> [faq] Fix link in Spanish App FAQ

.gitignore, content/faq/text-to-speech-android-tts/index.it.md
Also, fixed taxonomy for "Voice Directions" @gpesquero. We can leave "App" as is, as it is a commonly used neologism.
Signed-off-by: Luca Ceccarini <luca@decode.lc>
=> [faq] 🇮🇹 Reworked page Text-to-Speech on Android

content/faq/editing/advanced-editing/index.md, content/faq/editing/advanced-map-editing/index.md, sass/main.scss
Added an 'advanced osm editing' section to the faq, so this page can be linked to in https://github.com/organicmaps/organicmaps/pull/7748.
See also  #203
=> [faq] Added 'advanced osm editing' section

templates/shortcodes/references.md
Because looks like mostly it was already sorted.
=> references.md sort

content/_index.tr.md
Signed-off-by: Metehan Özyürek <metehanc8s9@hotmail.com>
=> Updated Turkish Translations

content/faq/map/how-to-create-a-route/index.pt-BR.md, templates/faq/embedded-faq.html
Added missing pt-BR question.
List of languages in embedded FAQ JS code is now generated by Zola.
=> FAQ improvements

content/faq/app/how-to-use-android-auto/index.fr.md, content/faq/app/which-ios-and-android-versions-are-supported/index.fr.md
=> Translate missing pages for application faq section

content/news/2024-07-15/392/index.fr.md, content/news/2024-07-15/_index.fr.md
=> Translate news to French for 15 07 2024

content/faq/app/how-to-use-android-auto/index.fr.md, content/faq/app/which-ios-and-android-versions-are-supported/index.fr.md
All is in the title.
Related to https://github.com/organicmaps/organicmaps.github.io/pull/254#pullrequestreview-2231866707
=> Hotfix for french version of app faq pages

content/faq/bookmarks/android-track-recording/index.de.md, content/faq/bookmarks/android-track-recording/index.es.md, content/faq/bookmarks/android-track-recording/index.fr.md, content/faq/bookmarks/android-track-recording/index.md, content/faq/bookmarks/android-track-recording/index.pl.md, content/faq/bookmarks/android-track-recording/index.pt-BR.md, content/faq/bookmarks/android-track-recording/index.pt.md, content/faq/bookmarks/android-track-recording/index.ru.md, content/faq/bookmarks/android-track-recording/index.tr.md, content/faq/bookmarks/android-track-recording/index.uk.md, content/faq/bookmarks/android-track-recording/index.zh-Hans.md, templates/faq/embedded-faq.html
Please review and propose translations into your language.
=> [faq] Add tracks recording in background section troubleshooting

content/news/2024-09-19/405/index.md, content/news/2024-09-19/_index.md, content/news/2024-10-07/406/index.md, content/news/2024-10-07/_index.md, content/news/2024-10-23/407/index.md, content/news/2024-10-23/_index.md, content/news/2024-11-12/408/index.md, content/news/2024-11-12/_index.md, content/news/2024-11-27/410/index.md, content/news/2024-11-27/_index.md
=> News for Sep-Nov releases

content/news/2024-12-20/411/index.md
This is just one of the reasons we do Pull Requests and don't push to master directly..
Another reason - this peace is heavily editorialized/opinionated. Its better to avoid posting such stories via official project channels. At the very least it should be clear its an editorial piece by a certain author (could you please amend and sign it?).
=> Fix typos/mistakes in the 4 years news item

content/faq/editing/advanced-map-editing/index.md, content/faq/editing/organic-maps-map-editing/index.md
Improved parts of the text from #203 and added it to the faq.
=> Add 'How can I edit the map in Organic Maps' page to faq

content/news/2025-01-26/413/index.md, content/news/2025-01-26/_index.md
=> January 2025.01.26 release announecement

content/privacy/index.md
May want to elaborate on app privacy vs obtaining of map files, checking for updates, sending debug logs, etc
=> Clarify location privacy
